name: NextJs Deployment to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build Next.js application
        run: npm run build

      - name: Upload files to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 23.22.231.0
          username: ubuntu
          key: "-----BEGIN RSA PRIVATE KEY-----MIIEowIBAAKCAQEAt9zUJ5aFp6Zp36BYUHfpNwUvcwDDsVNfYi0w0CVOqlQLadI8HLuE0M6N5AzHJE/Vk+OvaFN1FCj6aXAJh/zP0tA/Z03uUHGeWLjdaVbaCIoF7wSov9gh5qZmgpF9H85ShG4DoKEvrH37kqgD/XZ4EDWu5CEs2HWlcojA0px/4N9ZtJ1N/59qqDWXLohwcYgYU7uPm9A02wUj53iEt47FH2MI3aoeg0eymiTFHkAw8judWimQWWWzbJVuI1qDNNDz5E1TWJdfsehJ0/EupDjCjJa9Pd35GEHgK7z8fIDEelNoNb8aLf5FIEG3h/46xQIqcKY7fcC3S4H/L1YLLINOtQIDAQABAoIBAAz6Z3dL5q9IzdxdIx66+BlMImdJvIZ9zhPOAM4QdBcNy6hykI+upNdgXR+lz0C+6eKAhdclXPRJWDOtFt8kdz74OCGAnLvM6VJ16hsPaGCF7ZlLiOXRycLQKBg7UMu38pcqdNMXzZetZN6bQXzYqezq/SdZOCMnWsBU6tdy+IvU2WohwS4De0LJ3i7IL3k5v4O+mNQ2YDLQN0/6uxClCX46KzJS9L5zDRh46VhTLivucEDvCdEFEjFK7/6o3q+r+VNGRByX+BG03MMKTiPonMeWSDaxTiL5v4jbk5XU85UY65HrvTGKhHsG+HSSqC11/rDU2OjyJQ7A00gof9H+etkCgYEA7oFC0e7klqEvAg+CJ6UAEAIp4koj/acoy9yEqYXFfdiF/OU1bbZSoSJLON3saAYSD9wIqPrmK49s1G3C7r43lY73ve1Oor+y9581o+w0Fed351dkqspR9mTv1IxTHIXO/TnBL6uOnqL/L2P52occX83tLPZCGK8MK123eKCWPjMCgYEAxVl5Ee/uqoIJvQpOp3Y+uOEc/WfaPDpeKcSrTcgVFfRtLrJG69NG/uaHNoR58QmRsPHTuBsoBwOAaHrGGelydw5pbdvzXjkaEXbcBB8hFKwI0k38MWbYpHVHw3mAQT4XQG/pKE7gNZ9ExiVk9PzPGBCnB8oQmsxkAZXdcG4jB3cCgYBhwswP3vsFnxX0o0S3WVO4PBrM7ZTpEM6RGVerYPC9j7YEHjOTP+uIrtTkf1q6nNpkc8187jLQYh66yC7hy0hfXlXAHPhhj3AdPb4v7c6/t7wXMGRL+Vg1RdRkbAxZIaPhef3su0ZfUfKFi1ZLs5v2zSLNjjczhPTZBbYBlNlgrwKBgQCvWJ5AF8UhbsUkWCImnOOB9VKCvWGknd/IkNv8EkjZ5wGTugdVxbWRClcdU3vddLkkVNne/RIFmVDghCW8JDX2HrICUKneEDJfThKS/u2vpmN4KJ5pbo4TIbmPr0cLsRWLxWOO0vZX7pl2zQb0viNrqHAgdaNnRy+cUQIdwV4SZQKBgHA6AnFM+IzlWcsediQ0w2Cyyobswmwpl85lpXeMx5KXYiavnLgjmoDAOgXA+wXgWessbQv7VkQ4+VuV+8QnvKTZT4oODXVToWNBuOh3xBb/Tc3UT7SX5IzPnWkbEB6bNXxtztnMn0Ex+K/wh6piXw1niOwO3YumzSffkDDkovvq-----END RSA PRIVATE KEY-----"
          source: "."
          target: "/home/ubuntu/nextjs-app"
          rm: true
          strip_components: 1
          overwrite: true

      - name: Run deployment commands on EC2
        uses: appleboy/ssh-action@master
        with:
          host: 23.22.231.0
          username: ubuntu
          key: "-----BEGIN RSA PRIVATE KEY-----MIIEowIBAAKCAQEAt9zUJ5aFp6Zp36BYUHfpNwUvcwDDsVNfYi0w0CVOqlQLadI8HLuE0M6N5AzHJE/Vk+OvaFN1FCj6aXAJh/zP0tA/Z03uUHGeWLjdaVbaCIoF7wSov9gh5qZmgpF9H85ShG4DoKEvrH37kqgD/XZ4EDWu5CEs2HWlcojA0px/4N9ZtJ1N/59qqDWXLohwcYgYU7uPm9A02wUj53iEt47FH2MI3aoeg0eymiTFHkAw8judWimQWWWzbJVuI1qDNNDz5E1TWJdfsehJ0/EupDjCjJa9Pd35GEHgK7z8fIDEelNoNb8aLf5FIEG3h/46xQIqcKY7fcC3S4H/L1YLLINOtQIDAQABAoIBAAz6Z3dL5q9IzdxdIx66+BlMImdJvIZ9zhPOAM4QdBcNy6hykI+upNdgXR+lz0C+6eKAhdclXPRJWDOtFt8kdz74OCGAnLvM6VJ16hsPaGCF7ZlLiOXRycLQKBg7UMu38pcqdNMXzZetZN6bQXzYqezq/SdZOCMnWsBU6tdy+IvU2WohwS4De0LJ3i7IL3k5v4O+mNQ2YDLQN0/6uxClCX46KzJS9L5zDRh46VhTLivucEDvCdEFEjFK7/6o3q+r+VNGRByX+BG03MMKTiPonMeWSDaxTiL5v4jbk5XU85UY65HrvTGKhHsG+HSSqC11/rDU2OjyJQ7A00gof9H+etkCgYEA7oFC0e7klqEvAg+CJ6UAEAIp4koj/acoy9yEqYXFfdiF/OU1bbZSoSJLON3saAYSD9wIqPrmK49s1G3C7r43lY73ve1Oor+y9581o+w0Fed351dkqspR9mTv1IxTHIXO/TnBL6uOnqL/L2P52occX83tLPZCGK8MK123eKCWPjMCgYEAxVl5Ee/uqoIJvQpOp3Y+uOEc/WfaPDpeKcSrTcgVFfRtLrJG69NG/uaHNoR58QmRsPHTuBsoBwOAaHrGGelydw5pbdvzXjkaEXbcBB8hFKwI0k38MWbYpHVHw3mAQT4XQG/pKE7gNZ9ExiVk9PzPGBCnB8oQmsxkAZXdcG4jB3cCgYBhwswP3vsFnxX0o0S3WVO4PBrM7ZTpEM6RGVerYPC9j7YEHjOTP+uIrtTkf1q6nNpkc8187jLQYh66yC7hy0hfXlXAHPhhj3AdPb4v7c6/t7wXMGRL+Vg1RdRkbAxZIaPhef3su0ZfUfKFi1ZLs5v2zSLNjjczhPTZBbYBlNlgrwKBgQCvWJ5AF8UhbsUkWCImnOOB9VKCvWGknd/IkNv8EkjZ5wGTugdVxbWRClcdU3vddLkkVNne/RIFmVDghCW8JDX2HrICUKneEDJfThKS/u2vpmN4KJ5pbo4TIbmPr0cLsRWLxWOO0vZX7pl2zQb0viNrqHAgdaNnRy+cUQIdwV4SZQKBgHA6AnFM+IzlWcsediQ0w2Cyyobswmwpl85lpXeMx5KXYiavnLgjmoDAOgXA+wXgWessbQv7VkQ4+VuV+8QnvKTZT4oODXVToWNBuOh3xBb/Tc3UT7SX5IzPnWkbEB6bNXxtztnMn0Ex+K/wh6piXw1niOwO3YumzSffkDDkovvq-----END RSA PRIVATE KEY-----"
          script: |
            cd /home/ubuntu/nextjs-app
            npm install --production

            # Ensure PM2 is installed
            sudo npm install -g pm2

            # Restart or start PM2 process
            pm2 restart nextjs-app || pm2 start npm --name nextjs-app -- start